---
title: "PopGen"
author: "Hazel Daniels & Nick Carleson"
date: "30 March 2021"
output:
  word_document: default
  html_document: default
---

Following the tutorial found at https://grunwaldlab.github.io/Population_Genetics_in_R/gbs_analysis.html

```{r setup,include = FALSE}
knitr::opts_chunk$set(echo  =  TRUE)
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

#reading and manipulating data
library(vcfR)
library(readxl)
library(dplyr)

#distance tree
library(poppr)
library(ape)
library(viridis)

#MSN
library(igraph)

#PCA
library(ggplot2)

#DAPC
library(tidyr)
```

# Reading & manipulating data
```{r}
pram.VCF <- read.vcfR("Final.vcf.gz")

pop.data <- read_xlsx("population_data.wgs.xlsx",1)
EU1 <- subset(pop.data, pop.data$Lin == "EU1")

EU1$ID[!(EU1$ID %in% colnames(pram.VCF@gt)[-1])]
#showing which samples need removed


# removing filtered sites out

EU1 <- arrange(EU1, ID)

all(colnames(pram.VCF@gt)[-1] == EU1$ID)

pram.gl <- vcfR2genlight(pram.VCF)
ploidy(pram.gl) <- 2
pop(pram.gl) <- EU1$Year

pram.gl
```

# Distance Tree
```{r}
tree <- aboot(pram.gl, tree = "nj", 
              distance = bitwise.dist, 
              sample = 1, showtree = F, 
              cutoff = 50, quiet = T)

cols <- viridis(n = nPop(pram.gl), begin = 0, end = 1 )

#setting up tree
plot.phylo(tree, cex = 0.8, font = 2, adj = 0, 
           tip.color =  cols[pop(pram.gl)])
#add node labels (left)
nodelabels(tree$node.label, adj = c(1.3, -0.5), 
           frame = "n", cex = 0.8,font = 3, xpd = TRUE)
#add legend (right)
legend('top', legend = c("2001","2002","2003","2004","2005"),
       fill = cols, border = FALSE, bty = "n", cex = 0.5)
#add bottom axis
axis(side = 1)
#add title
title(xlab = 
        "Genetic distance (proportion of loci that are different)")
```

# Minimum Spanning Network
```{r}
pram.dist <- bitwise.dist(pram.gl)
pram.msn <- poppr.msn(pram.gl, pram.dist, showplot = FALSE, include.ties = T)

node.size <- rep(2, times = nInd(pram.gl))
names(node.size) <- indNames(pram.gl)
vertex.attributes(pram.msn$graph)$size <- node.size

set.seed(47)
plot_poppr_msn(pram.gl, pram.msn , gadj = 70,
               palette = viridis(n = nPop(pram.gl), 
                                 begin = 0, end = 1))
```

# Principal Components
```{r}
pram.pca <- glPca(pram.gl, nf = 3)
barplot(100*pram.pca$eig/sum(pram.pca$eig), 
        col = heat.colors(50), main="PCA Eigenvalues")
title(ylab="Percent of variance\nexplained", line = 2)
title(xlab="Eigenvalues", line = 1)

pram.pca.scores <- as.data.frame(pram.pca$scores)
pram.pca.scores$pop <- pop(pram.gl)

set.seed(47)
pl <- ggplot(pram.pca.scores, aes(x=PC1, y=PC2, colour=pop))+
  geom_point(size=2)+ 
  stat_ellipse(level = 0.95, size = 1)+
  scale_color_manual(values = cols)+
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 0)+ 
  theme_bw()

pl
```

# DAPC
```{r}
pram.dapc <- dapc(pram.gl, n.pca = 3, n.da = 2)

scatter(pram.dapc, col = cols, cex = 2, legend = TRUE, clabel = F, posi.leg = "bottomleft", scree.pca = TRUE,
        posi.pca = "topleft", cleg = 0.75)

compoplot(pram.dapc,col = cols, posi = 'top')

dapc.results <- as.data.frame(pram.dapc$posterior)
dapc.results$pop <- pop(pram.gl)
dapc.results$indNames <- rownames(dapc.results)
dapc.results <- pivot_longer(dapc.results, -c(pop, indNames))

head(dapc.results, n = 6)

colnames(dapc.results) <- c("Original_Pop","Sample","Assigned_Pop","Posterior_membership_probability")

head(dapc.results, n = 6)

q <- ggplot(dapc.results, aes(x=Sample, y=Posterior_membership_probability, fill=Assigned_Pop))+ 
  geom_bar(stat='identity')+ 
  scale_fill_manual(values = cols)+
  facet_grid(~Original_Pop, scales = "free")+
  theme(axis.text.x = element_text(angle = 90, 
                                   hjust = 1, 
                                   size = 8))
q
```